name: Node.js CI

on:
  workflow_dispatch:

  schedule:
    - cron: '*/10 * * * *'

  pull_request:
    branches:
      - main

jobs:
  check_changed:
    name: Check if foo dependency has changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: tj-actions/changed-files@v44
        id: changed_files
        with:
          files: package.json
      - name: Get dependency versions
        id: did_change
        if: steps.changed_files.outputs.any_changed == 'true'
        run: |
          current_val=$(cat package.json | jq -r .dependencies.foo)
          echo "current_val=${current_val}" >> "$GITHUB_OUTPUT"
          
          git checkout origin/${{github.base_ref}}
          previous_val=$(cat package.json | jq -r .dependencies.foo)
          echo "previous_val=${previous_val}" >> "$GITHUB_OUTPUT"
          
          git checkout ${{github.sha}}
          # git diff ${{github.sha}} origin/${{github.base_ref}}
    outputs:
      previous_val: ${{steps.did_change.outputs.PREVIOUS_VAL}}
      current_val: ${{steps.did_change.outputs.CURRENT_VAL}}


  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: node index.js

  do_stuff:
    needs: [check_changed]
    if: github.event_name == 'workflow_dispatch' ||
      github.event_name == 'schedule' ||
      needs.check_changed.outputs.previous_val != needs.check_changed.outputs.current_val
    runs-on: ubuntu-latest
    steps:
      - name: Do stuff
        run: |
          echo "${{needs.check_changed.outputs.previous_val}}"
          echo "${{needs.check_changed.outputs.current_val}}"
