name: Node.js CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  check_changed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: tj-actions/changed-files@v44
        id: changed_files
        with:
          files: package.json
      - id: did_change
        if: steps.changed_files.outputs.any_changed == 'true'
        run: |
          git diff ${{github.head_ref || github.ref_name}} ${{github.sha}}


  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: node index.js
